export enum WalletTypeEnum {
    VVIP = 0,
    INDIVIDUAL_PREPAID = 1,
    INDIVIDUAL_POSTPAID_CREDIT = 2,
    INDIVIDUAL_POSTPAID_BILLING = 3,
    CORPORATE_PREPAID = 4,
    CORPORATE_POSTPAID_CREDIT = 5,
    CORPORATE_POSTPAID_BILLIING = 6,
}